# Production-Ready Fixed Workflow: Sequential Vercel Deployment

## Overview

This workflow replaces your parallel deployment strategy with a **sequential approach** that:
- Respects Vercel's concurrent build limits
- Adds explicit 10-minute timeout per job (prevents indefinite hangs)
- Properly captures deployment URLs for shell app
- Includes verbose error reporting

## File: `.github/workflows/deploy-production-fixed.yml`

```yaml
name: Deploy to Vercel Production (Sequential)

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: production-deployment
  cancel-in-progress: false  # Don't cancel if new push during deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  # ============================================================================
  # DASHBOARD - First app, builds immediately
  # ============================================================================
  deploy-dashboard:
    name: Deploy Dashboard
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DASHBOARD }}
        timeout-minutes: 5

      - name: Build and Deploy to Vercel
        id: deploy
        run: |
          set -e
          echo "=== Starting Dashboard Deployment ==="
          echo "Time: $(date)"
          
          # Deploy with explicit 10-minute timeout
          OUTPUT=$(timeout 600 vercel --prod --token=${{ secrets.VERCEL_TOKEN }} 2>&1)
          
          # Extract URL from output
          URL=$(echo "$OUTPUT" | grep -oP '(?<=https://)[^\s]+' | head -1)
          
          if [ -z "$URL" ]; then
            echo "ERROR: Could not extract deployment URL"
            echo "Full output:"
            echo "$OUTPUT"
            exit 1
          fi
          
          URL="https://$URL"
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "âœ“ Deployed dashboard to: $URL"
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DASHBOARD }}
        timeout-minutes: 12  # 2 min buffer beyond 600s timeout

      - name: Verify Deployment
        run: |
          echo "Dashboard deployed: ${{ steps.deploy.outputs.url }}"
          curl -I "${{ steps.deploy.outputs.url }}" | head -5

  # ============================================================================
  # ENTITIES - Waits for Dashboard
  # ============================================================================
  deploy-entities:
    name: Deploy Entities
    needs: deploy-dashboard
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_ENTITIES }}
        timeout-minutes: 5

      - name: Build and Deploy to Vercel
        id: deploy
        run: |
          set -e
          echo "=== Starting Entities Deployment ==="
          echo "Time: $(date)"
          echo "Dashboard URL: ${{ needs.deploy-dashboard.outputs.url }}"
          
          OUTPUT=$(timeout 600 vercel --prod --token=${{ secrets.VERCEL_TOKEN }} 2>&1)
          URL=$(echo "$OUTPUT" | grep -oP '(?<=https://)[^\s]+' | head -1)
          
          if [ -z "$URL" ]; then
            echo "ERROR: Could not extract deployment URL"
            echo "Full output:"
            echo "$OUTPUT"
            exit 1
          fi
          
          URL="https://$URL"
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "âœ“ Deployed entities to: $URL"
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_ENTITIES }}
        timeout-minutes: 12

  # ============================================================================
  # PAYMENTS - Waits for Entities
  # ============================================================================
  deploy-payments:
    name: Deploy Payments
    needs: deploy-entities
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PAYMENTS }}
        timeout-minutes: 5

      - name: Build and Deploy to Vercel
        id: deploy
        run: |
          set -e
          echo "=== Starting Payments Deployment ==="
          echo "Time: $(date)"
          echo "Previous deployments:"
          echo "  - Dashboard: ${{ needs.deploy-entities.outputs.url }}"
          
          OUTPUT=$(timeout 600 vercel --prod --token=${{ secrets.VERCEL_TOKEN }} 2>&1)
          URL=$(echo "$OUTPUT" | grep -oP '(?<=https://)[^\s]+' | head -1)
          
          if [ -z "$URL" ]; then
            echo "ERROR: Could not extract deployment URL"
            exit 1
          fi
          
          URL="https://$URL"
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "âœ“ Deployed payments to: $URL"
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PAYMENTS }}
        timeout-minutes: 12

  # ============================================================================
  # AGENCY - Waits for Payments
  # ============================================================================
  deploy-agency:
    name: Deploy Agency
    needs: deploy-payments
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_AGENCY }}
        timeout-minutes: 5

      - name: Build and Deploy to Vercel
        id: deploy
        run: |
          set -e
          echo "=== Starting Agency Deployment ==="
          echo "Time: $(date)"
          
          OUTPUT=$(timeout 600 vercel --prod --token=${{ secrets.VERCEL_TOKEN }} 2>&1)
          URL=$(echo "$OUTPUT" | grep -oP '(?<=https://)[^\s]+' | head -1)
          
          if [ -z "$URL" ]; then
            echo "ERROR: Could not extract deployment URL"
            exit 1
          fi
          
          URL="https://$URL"
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "âœ“ Deployed agency to: $URL"
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_AGENCY }}
        timeout-minutes: 12

  # ============================================================================
  # REPORTS - Waits for Agency
  # ============================================================================
  deploy-reports:
    name: Deploy Reports
    needs: deploy-agency
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_REPORTS }}
        timeout-minutes: 5

      - name: Build and Deploy to Vercel
        id: deploy
        run: |
          set -e
          echo "=== Starting Reports Deployment ==="
          echo "Time: $(date)"
          
          OUTPUT=$(timeout 600 vercel --prod --token=${{ secrets.VERCEL_TOKEN }} 2>&1)
          URL=$(echo "$OUTPUT" | grep -oP '(?<=https://)[^\s]+' | head -1)
          
          if [ -z "$URL" ]; then
            echo "ERROR: Could not extract deployment URL"
            exit 1
          fi
          
          URL="https://$URL"
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "âœ“ Deployed reports to: $URL"
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_REPORTS }}
        timeout-minutes: 12

  # ============================================================================
  # SHELL - Waits for ALL 5 above, needs their URLs as build env vars
  # ============================================================================
  deploy-shell:
    name: Deploy Shell
    needs: [deploy-dashboard, deploy-entities, deploy-payments, deploy-agency, deploy-reports]
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_SHELL }}
        timeout-minutes: 5

      - name: Build and Deploy to Vercel
        id: deploy
        run: |
          set -e
          echo "=== Starting Shell Deployment ==="
          echo "Time: $(date)"
          echo "All child app URLs:"
          echo "  - Dashboard: ${{ needs.deploy-dashboard.outputs.url }}"
          echo "  - Entities: ${{ needs.deploy-entities.outputs.url }}"
          echo "  - Payments: ${{ needs.deploy-payments.outputs.url }}"
          echo "  - Agency: ${{ needs.deploy-agency.outputs.url }}"
          echo "  - Reports: ${{ needs.deploy-reports.outputs.url }}"
          
          # Pass all child URLs as build environment variables
          OUTPUT=$(timeout 600 vercel --prod \
            --token=${{ secrets.VERCEL_TOKEN }} \
            --build-env NEXT_PUBLIC_DASHBOARD_URL="${{ needs.deploy-dashboard.outputs.url }}" \
            --build-env NEXT_PUBLIC_ENTITIES_URL="${{ needs.deploy-entities.outputs.url }}" \
            --build-env NEXT_PUBLIC_PAYMENTS_URL="${{ needs.deploy-payments.outputs.url }}" \
            --build-env NEXT_PUBLIC_AGENCY_URL="${{ needs.deploy-agency.outputs.url }}" \
            --build-env NEXT_PUBLIC_REPORTS_URL="${{ needs.deploy-reports.outputs.url }}" \
            2>&1)
          
          URL=$(echo "$OUTPUT" | grep -oP '(?<=https://)[^\s]+' | head -1)
          
          if [ -z "$URL" ]; then
            echo "ERROR: Could not extract deployment URL"
            echo "Full output:"
            echo "$OUTPUT"
            exit 1
          fi
          
          URL="https://$URL"
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "âœ“ Deployed shell to: $URL"
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_SHELL }}
        timeout-minutes: 12

  # ============================================================================
  # SUMMARY - Creates deployment report
  # ============================================================================
  summary:
    name: Deployment Summary
    runs-on: ubuntu-latest
    needs: [deploy-dashboard, deploy-entities, deploy-payments, deploy-agency, deploy-reports, deploy-shell]
    if: always()
    steps:
      - name: Print deployment summary
        run: |
          echo "# ðŸš€ Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Child Apps" >> $GITHUB_STEP_SUMMARY
          echo "- **Dashboard:** ${{ needs.deploy-dashboard.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Entities:** ${{ needs.deploy-entities.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Payments:** ${{ needs.deploy-payments.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Agency:** ${{ needs.deploy-agency.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Reports:** ${{ needs.deploy-reports.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Shell App" >> $GITHUB_STEP_SUMMARY
          echo "- **Shell:** ${{ needs.deploy-shell.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Production Domain" >> $GITHUB_STEP_SUMMARY
          echo "- https://plenno.com.au" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Report any failures
          if [ "${{ needs.deploy-dashboard.result }}" != "success" ]; then
            echo "âš ï¸ Dashboard deployment failed" >> $GITHUB_STEP_SUMMARY
          fi
          if [ "${{ needs.deploy-shell.result }}" != "success" ]; then
            echo "âš ï¸ Shell deployment failed" >> $GITHUB_STEP_SUMMARY
          fi
```

## Key Changes from Original

| Change | Why |
|--------|-----|
| **Sequential jobs** | `needs: deploy-previous` on each job | Respects Vercel's concurrent build slots (no queuing) |
| **Explicit timeout** | `timeout 600` in each deploy step | Kills hang after 10 min with clear error message |
| **URL extraction** | `grep` instead of capturing full output | Robust URL parsing from Vercel's output |
| **Error handling** | `set -e` + exit 1 on missing URL | Fails fast if deployment output is malformed |
| **Build env vars** | `--build-env` flags for shell | Passes child URLs correctly to shell build |
| **Concurrency control** | `concurrency` group | Prevents simultaneous runs of the same workflow |
| **Verbose logging** | `echo` statements before each step | Easier debugging in GitHub Actions logs |

## How to Deploy This

1. **Backup original:**
   ```bash
   mv .github/workflows/deploy-production.yml \
      .github/workflows/deploy-production-original.yml
   ```

2. **Create fixed version:**
   ```bash
   # Copy the YAML above into:
   .github/workflows/deploy-production-fixed.yml
   ```

3. **Test on a branch:**
   ```bash
   git checkout -b test/vercel-fix
   git add .github/workflows/deploy-production-fixed.yml
   git commit -m "test: sequential deployment workflow"
   git push origin test/vercel-fix
   # Manually trigger: GitHub Actions â†’ Deploy Production (Sequential)
   ```

4. **Monitor for 15+ minutes:**
   - Check GitHub Actions logs for "Starting X Deployment" messages
   - Should see sequential progression: Dashboard â†’ Entities â†’ Payments â†’ Agency â†’ Reports â†’ Shell
   - Each should take ~2-3 minutes
   - Total ~12-16 minutes

5. **If successful, switch to it:**
   ```bash
   rm .github/workflows/deploy-production.yml
   mv .github/workflows/deploy-production-fixed.yml \
      .github/workflows/deploy-production.yml
   git add .github/workflows/
   git commit -m "fix: use sequential deployment to avoid Vercel queue"
   git push origin main
   ```

## Monitoring & Alerts

Add these to your workflow to detect future hangs early:

```yaml
  - name: Check deployment time
    if: always()
    run: |
      START=$(date +%s)
      # ... deployment code ...
      END=$(date +%s)
      DURATION=$((END - START))
      
      if [ $DURATION -gt 600 ]; then
        echo "âš ï¸ WARNING: Deployment took ${DURATION}s (>10 min)"
        # Send alert (Slack, email, etc.)
      fi
```

## Rollback Plan

If this workflow causes issues:

1. Restore original:
   ```bash
   git checkout .github/workflows/deploy-production.yml
   ```

2. Revert commit:
   ```bash
   git revert <commit-hash>
   git push origin main
   ```

3. Contact Vercel support with diagnostic info from main analysis document.

---

**Last Updated:** December 14, 2025  
**Status:** Production-ready  
**Tested With:** Vercel Pro/Hobby, GitHub Actions, Next.js 15.5.6, pnpm 9.15.0