#!/bin/bash
# Vercel Configuration Setup Script for Pleeno Monorepo
# This script provides the configuration needed for each Vercel project

echo "=================================================="
echo "VERCEL PROJECT CONFIGURATION FOR PLEENO MONOREPO"
echo "=================================================="
echo ""
echo "You need to configure 6 separate Vercel projects."
echo "For EACH project, use these settings in Vercel Dashboard:"
echo ""
echo "=================================================="
echo "1. SHELL APP (Authentication Service)"
echo "=================================================="
echo "Project Name: pleeno-shell-prod"
echo "Domain: shell.plenno.com.au"
echo ""
echo "Settings → General:"
echo "  Root Directory: apps/shell"
echo "  Framework Preset: Next.js"
echo ""
echo "Settings → Build & Deployment:"
echo "  Build Command: turbo build --filter=shell"
echo "  Output Directory: apps/shell/.next"
echo "  Install Command: npm install"
echo ""
echo "=================================================="
echo "2. DASHBOARD APP"
echo "=================================================="
echo "Project Name: pleeno-dashboard-prod"
echo "Domain: dashboard.plenno.com.au"
echo ""
echo "Settings → General:"
echo "  Root Directory: apps/dashboard"
echo "  Framework Preset: Next.js"
echo ""
echo "Settings → Build & Deployment:"
echo "  Build Command: turbo build --filter=dashboard"
echo "  Output Directory: apps/dashboard/.next"
echo "  Install Command: npm install"
echo ""
echo "=================================================="
echo "3. AGENCY APP"
echo "=================================================="
echo "Project Name: pleeno-agency-prod"
echo "Domain: agency.plenno.com.au"
echo ""
echo "Settings → General:"
echo "  Root Directory: apps/agency"
echo "  Framework Preset: Next.js"
echo ""
echo "Settings → Build & Deployment:"
echo "  Build Command: turbo build --filter=agency"
echo "  Output Directory: apps/agency/.next"
echo "  Install Command: npm install"
echo ""
echo "=================================================="
echo "4. ENTITIES APP"
echo "=================================================="
echo "Project Name: pleeno-entities-prod"
echo "Domain: entities.plenno.com.au"
echo ""
echo "Settings → General:"
echo "  Root Directory: apps/entities"
echo "  Framework Preset: Next.js"
echo ""
echo "Settings → Build & Deployment:"
echo "  Build Command: turbo build --filter=entities"
echo "  Output Directory: apps/entities/.next"
echo "  Install Command: npm install"
echo ""
echo "=================================================="
echo "5. PAYMENTS APP"
echo "=================================================="
echo "Project Name: pleeno-payments-prod"
echo "Domain: payments.plenno.com.au"
echo ""
echo "Settings → General:"
echo "  Root Directory: apps/payments"
echo "  Framework Preset: Next.js"
echo ""
echo "Settings → Build & Deployment:"
echo "  Build Command: turbo build --filter=payments"
echo "  Output Directory: apps/payments/.next"
echo "  Install Command: npm install"
echo ""
echo "=================================================="
echo "6. REPORTS APP"
echo "=================================================="
echo "Project Name: pleeno-reports-prod"
echo "Domain: reports.plenno.com.au"
echo ""
echo "Settings → General:"
echo "  Root Directory: apps/reports"
echo "  Framework Preset: Next.js"
echo ""
echo "Settings → Build & Deployment:"
echo "  Build Command: turbo build --filter=reports"
echo "  Output Directory: apps/reports/.next"
echo "  Install Command: npm install"
echo ""
echo "=================================================="
echo "ENVIRONMENT VARIABLES (for ALL projects)"
echo "=================================================="
echo "Add these to EACH project's Environment Variables:"
echo ""
echo "NEXT_PUBLIC_COOKIE_DOMAIN=.plenno.com.au"
echo "NEXT_PUBLIC_SHELL_URL=https://shell.plenno.com.au"
echo "NEXT_PUBLIC_APP_URL=https://shell.plenno.com.au"
echo "NEXT_PUBLIC_DASHBOARD_URL=https://dashboard.plenno.com.au"
echo "NEXT_PUBLIC_AGENCY_URL=https://agency.plenno.com.au"
echo "NEXT_PUBLIC_ENTITIES_URL=https://entities.plenno.com.au"
echo "NEXT_PUBLIC_PAYMENTS_URL=https://payments.plenno.com.au"
echo "NEXT_PUBLIC_REPORTS_URL=https://reports.plenno.com.au"
echo ""
echo "Plus your Supabase and other service keys:"
echo "NEXT_PUBLIC_SUPABASE_URL=<your-supabase-url>"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=<your-supabase-anon-key>"
echo "SUPABASE_SERVICE_ROLE_KEY=<your-service-role-key>"
echo "DATABASE_URL=<your-database-url>"
echo ""
echo "=================================================="
echo "IMPORTANT NOTES:"
echo "=================================================="
echo "1. Each project must be linked to the SAME GitHub repo"
echo "2. Each project must have different Root Directory settings"
echo "3. Build commands use turbo filters for efficiency"
echo "4. All projects share the same environment variables"
echo "5. Cookie domain MUST have dot prefix for subdomain sharing"
echo ""